spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: eralpzeydan
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-very-long-secret-key-your-very-long-secret-key
  expiration: 86400000
