spring:
  application:
    name: ecommerce

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:eralpzeydan}
    password: ${DB_PASSWORD:123}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  cache:
    type: redis

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-very-long-secret-key-your-very-long-secret-key
  expiration: 86400000

logging:
  level:
    root: INFO
    com.eralp.ecommerce: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
